# Generated by Django 2.1 on 2019-03-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audtech_analytics', '0003_auto_20190313_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='AccountCategory',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='AuthorisedBy',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='CreatedBy',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='CurrencyCode',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='DivisionCode',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='DocumentHeaderText',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='EntityCode',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='GroupName',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='JournalNumber',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='JournalType',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='MainAccountCode',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='MainAccountName',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='ReferenceNo',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='ShortText',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='Splitbetweenheads',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='StatusPostedUnposted',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='SubAccountCode',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='SubAccountName',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='TaxReference',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='TransactionType',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='Year',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='client',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='engangement',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='user_id',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
