# Generated by Django 2.1 on 2019-03-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audtech_analytics', '0004_auto_20190313_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='ShortText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
