# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 00:46
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audtech_analytics', '0005_auto_20190313_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\python\\audtech_env132018\\audtech_project\\media'), upload_to=''),
        ),
    ]
